### ISSUE TITLE
bug in decoder

### ISSUE THREAD

**Issue by nimasdj** [jtrumbull/XMLParser#1]
It seems there is a bug in decoder, consider this xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<loginshare>
<result>1</result>
<user>
<usergroup>Registered</usergroup>
<fullname>haha</fullname>
<emails>
<email>hhs@dhdh.com</email>
<name>hg</name>
</emails>
</user>
</loginshare>
```

It turns it to this array:

```
Array
(
    [result] => 1
    [user] => Array
        (
            [usergroup] => Registered
            [fullname] => haha
            [emails] => Array
                (
                    [email] => hhs@dhdh.com
                    [name] => hg
                    [0] => 
                )
            [0] => 
        )
)
```

Why this [0] element array is there? encoding back this array will result in <item/> in xml.
Would you fix it?

**Comment by jtrumbull** [comment]
Fixed
@nimasdj, also note that the I nested this class inside of a namespace -you will now need to call:

``` php
use XMLParser\XMLparser;

// Your application....

$array = XMLparser::decode($xml_string);
```

-or alternatively in-line:

``` php
$array = XMLParser\XMLparser::decode($xml_string);
```

**Comment by nimasdj** [comment]
Have you committed changes in packagist too that I can install it via composer? What is the version?

**Comment by nimasdj** [comment]
I suggest it just returns an encoded json, end-user will have the choice to decode it as object or as array. I believe other users will appreciate this feature too.
If you are not considering this feature request, please advice how can I customize it to do so.

**Comment by nimasdj** [comment]
As about previous feature request it even be too much better to add two methods, one returns it as array, one returns it as stdObject. Would you please consider this feature request?

**Comment by jtrumbull** [comment]
Release v1.0.0 + created composer.json

**Comment by nimasdj** [comment]
@jtrumbull Why not considering to add two decoder methods, one returns xml as stdObject and one returns it as array? Does this mean I should pass the returned decoder array to arrayToStdObject method again?
