### ISSUE TITLE
stdObject to xml

### ISSUE THREAD

**Issue by nimasdj** [jtrumbull/XMLParser#5]
would consider to add a feature for stdObject to xml?

**Comment by jtrumbull** [comment]
Done.

**Comment by nimasdj** [comment]
@jtrumbull Does this mean, first I should use objectToArray to convert the object first, then pass the returned array to encode method?

**Comment by nimasdj** [comment]
@jtrumbull what about if I don't have array at hand and I just have a stdObject and I want to convert it into xml?

**Comment by jtrumbull** [comment]
@nimasdj : Personally, assuming that I have a choice, I would pre-process the object-to-array conversion -primarily for control over what is being passed to the client. However, the aforementioned change allows for both (see [Example # 2](https://github.com/jtrumbull/xml-parser/blob/master/tests/example2.php)).

**Comment by nimasdj** [comment]
@jtrumbull 

> object-to-array conversion

Would consider to add an stdObjectToArray method? As you have added arrayToObject method already, I think the reverse method will be very usefull too. This case, we can have both input/output as both array/object as desired. I hope you consider this feature.

**Comment by nimasdj** [comment]
@jtrumbull sorry I got confused, I see objectToArray is already available, I meant to say to add arrayToObject, if we need the returned decoded result as object instead of array, consider this please?
