### ISSUE TITLE
composer.json

### ISSUE THREAD

**Issue by phplicengine** [jtrumbull/XMLParser#6]
Hello,
May we ask please add a composer.json file and integrate this Git repository with packagist?

**Comment by jtrumbull** [comment]
Done

**Comment by jtrumbull** [comment]
package is available @ jtrumbull/xml-parser

**Comment by nimasdj** [comment]
@jtrumbull 
I think phplicengine gave a good suggestion, but you did a mistake:
You should rename the class as XMLParser.php and move it to a folder /src/XMLParser (the same folder name as namespace), then in composer.json add a psr-4 autoloader with 
"XMLParser\": "src/XMLParser"
with this current composer.json, there is no benefit.

**Comment by nimasdj** [comment]
@jtrumbull 
I refined composer.json to create autoloader and edited readme and examples as appropriate. I hope you consider PR #9  to merge it as your current composer.json has no benefit.
